### ISSUE TITLE
concurrent map read and map write

### ISSUE THREAD

**Issue by lockp111** [GianlucaGuarini/go-observable#4]
some times,it will throw "error:concurrent map read and map write" in golang 1.9

**Comment by GianlucaGuarini** [comment]
i can not reproduce the issue in go1.9.2 everything works fine. Could you please add a failing example?

**Comment by lockp111** [comment]
fatal error: concurrent map read and map write goroutine 1519 [running]: runtime.throw(0x17baed5, 0x21) /Users/tangwanwan/homebrew/Cellar/go/1.8.3/libexec/src/runtime/panic.go:596 +0x95 fp=0xc4208485d0 sp=0xc4208485b0 runtime.mapaccess1_faststr(0x16c9580, 0xc4202641e0, 0xc42067e4c0, 0x14, 0x13) /Users/tangwanwan/homebrew/Cellar/go/1.8.3/libexec/src/runtime/hashmap_fast.go:217 +0x4cf fp=0xc420848630 sp=0xc4208485d0 github.com/GianlucaGuarini/go-observable.(*Observable).removeEvent(0xc420262050, 0xc42067e4c0, 0x14, 0x179a620, 0xc4207dc860) /Users/tangwanwan/Code/Futures/FutureBao/bridge/lib/src/github.com/GianlucaGuarini/go-observable/helpers.go:41 +0x149 fp=0xc420848740 sp=0xc420848630 github.com/GianlucaGuarini/go-observable.(*Observable).Off(0xc420262050, 0xc42067e4c0, 0x14, 0xc4208487c0, 0x1, 0x1, 0x0) /Users/tangwanwan/Code/Futures/FutureBao/bridge/lib/src/github.com/GianlucaGuarini/go-observable/observable.go:74 +0x112 fp=0xc420848788 sp=0xc420848740 futuresbridge/eventbus.RpcSub.func2() /Users/tangwanwan/Code/Futures/FutureBao/bridge/src/futuresbridge/eventbus/eventbus.go:38 +0x82 fp=0xc4208487e0 sp=0xc420848788 runtime.goexit() /Users/tangwanwan/homebrew/Cellar/go/1.8.3/libexec/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4208487e8 sp=0xc4208487e0 created by github.com/tangyi1989/ws-jsonrpc2.(*Conn).ternimated /Users/tangwanwan/Code/Futures/FutureBao/bridge/lib/src/github.com/tangyi1989/ws-jsonrpc2/conn.go:37 +0xa6

Regards Harman Peng

**Comment by GianlucaGuarini** [comment]
hi thanks but i was not asking your error log message. I would like to see the issue in a 10 lines of code example if it's possible.
